config/routes.rb
Rails.application.routes.draw do
  get 'saidas/new'
  get 'saidas/create'
  get 'entradas/new'
  get 'entradas/create'
  resources :fritadeiras

  #index da pagina de dashboard
  root 'dashboard#index'

  ### Rotas Category ###
  resources :categories

  ### Rotas Fritadeiras ###
  resources :fritadeiras

  ### Rotas estoque ###
  resources :estoques

  ### Entradas ###
  resources :entradas

  ### Saidas ###
  resources :saidas

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/classe.rb
class Classe < ApplicationRecord
end

app/models/entrada.rb
class Entrada < ApplicationRecord
  belongs_to :estoque
  belongs_to :fritadeira


end

app/models/estoque.rb
class Estoque < ApplicationRecord
  belongs_to :fritadeira
  has_many :entrada, dependent: :destroy
  has_many :saida, dependent: :destroy



end

app/models/fritadeira.rb
class Fritadeira < ApplicationRecord
  belongs_to :category

  enum capacidade: { '3 litros' => 3, '5 litros' => 5, '7 litros' => 7, '10 litros' => 10, '12 litros' => 12, '14 litros' => 14 }
  enum voltagem: { '110v' => 0, '220v' => 1 }


end

app/models/saida.rb
class Saida < ApplicationRecord
  belongs_to :estoque
  belongs_to :fritadeira
end

app/controllers/classe_controller.rb
class ClasseController < ApplicationController
end

app/controllers/estoques_controller.rb
class EstoquesController < ApplicationController
    def index
      @estoques = Estoque.all
      @fritadeiras = Fritadeira.all
    end
    
    def new
        @estoque = Estoque.new
        @fritadeiras = Fritadeira.all
    end
    
    def create
      @estoque = Estoque.new(estoque_params)
      fritadeira_id = params[:estoque][:fritadeira_id]
      @estoque.fritadeira = Fritadeira.find(fritadeira_id)
  
      respond_to do |format|
        if @estoque.save
          format.html { redirect_to estoques_path, notice: "Fritadeira adicionada ao estoque!" }
        else
          format.html { render :new }
        end
      end
    end

    def destroy
      @estoque = Estoque.find(params[:id])
      @estoque.destroy
      redirect_to estoques_path, alert: 'Produto removido do controle de estoque.'
    end

    def edit
      @estoque = Estoque.find(params[:id])
    end 

    def update
      @estoque = Estoque.find(params[:id])
      if @estoque.update(estoque_params)
        redirect_to estoques_path, notice: 'Categoria atualizada com sucesso.'
      else
        render :edit
      end    
    end
    
    def show
    end

    

    


      
    private
  
    def estoque_params
      params.require(:estoque).permit(:q_atual, :q_min, :q_max, :fritadeira_id)
    end
end

app/controllers/saidas_controller.rb
class SaidasController < ApplicationController
  def new
    @estoque = Estoque.find(params[:estoque_id])
    @fritadeira = @estoque.fritadeira
    @saida = Saida.new
    @fritadeira_info = "#{@fritadeira.cod_interno} - #{@fritadeira.voltagem}"
  end

  def create
    @saida = Saida.new(saida_params)
    if @saida.save
      @estoque = Estoque.find(saida_params[:estoque_id])
      q_remover = saida_params[:q_remover].to_i
      @estoque.q_atual -= q_remover
      @estoque.save
      redirect_to estoques_path, notice: "Saida de mercadoria adicionada com sucesso!"
    else
      render :new
    end
  end

  private

  def saida_params
    params.require(:saida).permit(:q_remover, :origem_saida, :date, :estoque_id, :fritadeira_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/classe_helper.rb
module ClasseHelper
end

app/helpers/classificacao_helper.rb
module ClassificacaoHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/helpers/estoque_helper.rb
module EstoqueHelper
end

app/helpers/fritadeiras_helper.rb
module FritadeirasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/saidas_helper.rb
module SaidasHelper
end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/views/estoques/edit.html.erb
<div class="conteudo_titulo">  
    <h1>Editar quantidade minima e máxima</h1>
</div>
<hr/>
<br>
<div class="conteudo_infos mx-auto" style="width: 300px;">

    <%= form_with(model: @estoque, local: true) do |form| %>
        <h2><%= @estoque.fritadeira.cod_interno %> - <%= @estoque.fritadeira.voltagem %></h2>
        <hr/>

        <div class="mb-3">
            <%= form.label :q_min, 'Quantidade Minima', class: "form-label" %>
            <%= form.text_field :q_min, class: "form-control" %>
        </div>

        <div class="mb-3">
            <%= form.label :q_max, 'Quantidade máxima', class: "form-label" %>
            <%= form.text_field :q_max, class: "form-control" %>
        </div>

        <div class="mt-3">
            <%= form.submit 'Salvar', class: "btn btn-primary" %>
            <%= link_to 'Voltar', estoques_path, class: "btn btn-danger" %>
            
        </div>

    

    <% end %> 
</div>     

app/views/estoques/index.html.erb
<div class="conteudo_titulo">  
    <h1>Estoque</h1>
</div>
<hr/>
<br>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Código Interno</th>
                <th>Voltagem</th>
                <th>Quantidade em Estoque</th>
                <th>Quantidade Mínima</th>
                <th>Editar</th>
                <th>Entrada</th>
                <th>Saída</th>
                <th>Excluir do estoque</th>
            </tr>
        </thead>
        <tbody>
            <% @estoques.each do |estoque| %>
                <tr>
                    <td><%= estoque.fritadeira.cod_interno %></td>                          
                    <td><%= estoque.fritadeira.voltagem %></td>
                    <td><%= estoque.q_atual %></td>
                    <td><%= estoque.q_min %></td>
                    <td><%= link_to 'Editar', edit_estoque_path(estoque), class: 'btn btn-primary' %></td>
                    <td><%= link_to 'Entrada', new_entrada_path(estoque_id: estoque.id), class: 'btn btn-success' %></td>
                    <td><%= link_to 'Saída', new_saida_path(estoque_id: estoque.id), class: 'btn btn-warning' %></td>
                    <td><%= link_to 'Excluir Dados do Estoque', estoque, method: :delete, data: { confirm: 'Tem certeza que deseja excluir este estoque?' }, class: 'btn btn-danger' %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <%= link_to 'Adicionar produto ao estoque', new_estoque_path, class: 'btn btn-primary' %> 
</div>

app/views/estoques/new.html.erb
<div class="conteudo_titulo">  
    <h1>Adicionar Produto ao estoque</h1>
</div>
<hr/>
<br>    
<div class="conteudo_infos mx-auto" style="width: 300px;">
    <%= form_with(model: @estoque, local: true) do |form| %>
        <% if @estoque.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@estoque.errors.count, "erro") %> ocorreu ao salvar a categoria:</h2>
                <ul>
                <% @estoque.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
                </ul>
            </div>
        <% end %>
        <div class="mb-3">
            <%= form.label :fritadeira_id, "Fritadeira", class: "form-label" %>
            <select class="form-select" aria-label="Selecione uma fritadeira" name="estoque[fritadeira_id]">
                <% @fritadeiras.each do |fritadeira| %>
                <% fritadeira_label = "#{fritadeira.cod_interno} - #{fritadeira.voltagem}" %>    
                <% if fritadeira.id == 1 %>
                    <option value="<%= fritadeira.id %>" selected><%= fritadeira_label %></option>
                <% else %>
                    <option value="<%= fritadeira.id %>"><%= fritadeira_label %></option>
                <% end %>    
                <% end %>
            </select>
        </div>


        <div class="mb-3">
            <%= form.label :q_atual, "Quantidade Atual", class: "form-label" %>
            <%= form.number_field :q_atual, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= form.label :q_min, "Quantidade Minima", class: "form-label" %>
            <%= form.number_field :q_min, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= form.label :q_max, "Quantidade Maxima", class: "form-label" %>
            <%= form.number_field :q_max, class: "form-control" %>
        </div>

        <div class="mt-3">
            <%= form.submit 'Salvar', class: "btn btn-primary" %>
            <%= link_to 'Voltar', estoques_path, class: "btn btn-danger" %>
        </div>
        

        
    <% end %>
    
</div>