config/routes.rb
Rails.application.routes.draw do
  get 'saidas/new'
  get 'saidas/create'
  get 'entradas/new'
  get 'entradas/create'
  resources :fritadeiras

  #index da pagina de dashboard
  root 'dashboard#index'

  ### Rotas Category ###
  resources :categories

  ### Rotas Fritadeiras ###
  resources :fritadeiras

  ### Rotas estoque ###
  resources :estoques

  ### Entradas ###
  resources :entradas

  ### Saidas ###
  resources :saidas

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/classe.rb
class Classe < ApplicationRecord
end

app/models/entrada.rb
class Entrada < ApplicationRecord
  belongs_to :estoque
  belongs_to :fritadeira


end

app/models/estoque.rb
class Estoque < ApplicationRecord
  belongs_to :fritadeira
  has_many :entrada, dependent: :destroy
  has_many :saida, dependent: :destroy



end

app/models/fritadeira.rb
class Fritadeira < ApplicationRecord
  belongs_to :category

  enum capacidade: { '3 litros' => 3, '5 litros' => 5, '7 litros' => 7, '10 litros' => 10, '12 litros' => 12, '14 litros' => 14 }
  enum voltagem: { '110v' => 0, '220v' => 1 }


end

app/models/saida.rb
class Saida < ApplicationRecord
  belongs_to :estoque
  belongs_to :fritadeira
end

app/controllers/classe_controller.rb
class ClasseController < ApplicationController
end

app/controllers/fritadeiras_controller.rb
class FritadeirasController < ApplicationController
  before_action :set_fritadeira, only: %i[ show edit update destroy ]

  # GET /fritadeiras or /fritadeiras.json
  def index
    @fritadeiras = Fritadeira.all.sort_by { |fritadeira| [fritadeira.cod_interno[/[^\d]+/], fritadeira.cod_interno[/\d+/].to_i] }
  end

  # GET /fritadeiras/1 or /fritadeiras/1.json
  def show
  end

  # GET /fritadeiras/new
  def new
    @fritadeira = Fritadeira.new
    
  end

  # GET /fritadeiras/1/edit
  def edit
  end

  # POST /fritadeiras or /fritadeiras.json
  def create
    @fritadeira = Fritadeira.new(fritadeira_params)

    respond_to do |format|
      if @fritadeira.save
        format.html { redirect_to fritadeiras_path, notice: "Fritadeira criada com sucesso!" }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fritadeira.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fritadeiras/1 or /fritadeiras/1.json
  def update
    respond_to do |format|
      if @fritadeira.update(fritadeira_params)
        format.html { redirect_to fritadeiras_path, notice: "Fritadeira alterada com sucesso." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fritadeiras/1 or /fritadeiras/1.json
  def destroy
    @fritadeira.destroy

    respond_to do |format|
      format.html { redirect_to fritadeiras_url, alert: "Fritadeira excluida com sucesso." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fritadeira
      @fritadeira = Fritadeira.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fritadeira_params
      params.require(:fritadeira).permit(:modelo, :cod_interno, :capacidade, :voltagem, :category_id, :classe_id)
    end
end

app/controllers/saidas_controller.rb
class SaidasController < ApplicationController
  def new
    @estoque = Estoque.find(params[:estoque_id])
    @fritadeira = @estoque.fritadeira
    @saida = Saida.new
    @fritadeira_info = "#{@fritadeira.cod_interno} - #{@fritadeira.voltagem}"
  end

  def create
    @saida = Saida.new(saida_params)
    if @saida.save
      @estoque = Estoque.find(saida_params[:estoque_id])
      q_remover = saida_params[:q_remover].to_i
      @estoque.q_atual -= q_remover
      @estoque.save
      redirect_to estoques_path, notice: "Saida de mercadoria adicionada com sucesso!"
    else
      render :new
    end
  end

  private

  def saida_params
    params.require(:saida).permit(:q_remover, :origem_saida, :date, :estoque_id, :fritadeira_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/classe_helper.rb
module ClasseHelper
end

app/helpers/classificacao_helper.rb
module ClassificacaoHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/helpers/estoque_helper.rb
module EstoqueHelper
end

app/helpers/fritadeiras_helper.rb
module FritadeirasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/saidas_helper.rb
module SaidasHelper
end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/views/fritadeiras/edit.html.erb
<div class="conteudo_titulo">
        <h1>Editar Fritadeira</h1>
    </div>
    <hr/>
    <br>
    <div class="conteudo_infos mx-auto" style="width: 300px;">
        <%= form_with(model: @fritadeira, local: true) do |form| %>
            <% if @fritadeira.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@fritadeira.errors.count, "erro") %> ocorreu ao salvar a categoria:</h2>
                <ul>
                <% @fritadeira.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
                </ul>
            </div>
            <% end %>
        
            
        <div class="mb-3">
            <%= form.label :modelo, class: "form-label" %>
            <%= form.text_field :modelo, class: "form-control" %>
        </div>

        <div class="mb-3">
            <%= form.label :Cod_interno, "Codigo Interno", class: "form-label" %>
            <%= form.text_field :cod_interno, class: "form-control" %>
        </div>

        <div class="mb-3">
            <%= form.label :capacidade, class: "form-label" %>
            <%= form.select :capacidade, Fritadeira.capacidades.keys.map { |key| [key, key] }, { prompt: "Selecione a capacidade" }, class: "form-select" %>
        </div>

        <div class="mb-3">
            <%= form.label :voltagem, class: "form-label" %>
            <%= form.select :voltagem, Fritadeira.voltagems.keys.map { |key| [key.capitalize, key] }, { prompt: "Selecione a voltagem" }, class: "form-select" %>
        </div>

                    
        <div class="mb-3">
            <%= form.label :category_id, "Categoria", class: "form-label" %>
            <select class="form-select" aria-label="Selecione uma categoria" name="fritadeira[category_id]">
                <option selected disabled>Selecione uma categoria</option>
                <% Category.all.each do |category| %>
                <option value="<%= category.id %>"><%= category.name %></option>
                <% end %>
            </select>
        </div>
        
            <div class="mt-3">
            <%= form.submit 'Salvar', class: "btn btn-primary" %>
            <%= link_to 'Voltar', fritadeira_path, class: "btn btn-danger" %>
            </div>
        <% end %>

    </div>
</div>    

app/views/fritadeiras/index.html.erb
<div class="conteudo_titulo">
    <h1>Todas fritadeiras</h1>
</div>
<hr/>
<br>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>codigo interno</th>
                <th>voltagem</th>
                <th>categoria</th>
                <th>Editar</th>
                <th>Excluir</th>
                <!-- Se você tiver mais colunas, adicione aqui -->
            </tr>
        </thead>
        <tbody>
            <% @fritadeiras.each do |fritadeira| %>
                <tr>
                    <td>
                        <%= fritadeira.cod_interno %>
                    </td>               
                    <td>
                        <%= fritadeira.voltagem %>
                    </td>
                    <td>
                        <%= fritadeira.category.name %>
                    </td>
                    <td><%= link_to 'Editar', edit_fritadeira_path(fritadeira), class: 'btn btn-primary' %></td>
                    <td><%= link_to 'Excluir', fritadeira_path(fritadeira), method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-danger' %></td>
                    
                    
                    <!-- Se você tiver mais colunas, adicione aqui -->
                </tr>
            <% end %>
        </tbody>
    </table>
    <%= link_to 'Nova Fritadeira', new_fritadeira_path, class: 'btn btn-primary' %>

app/views/fritadeiras/new.html.erb
<div class="conteudo_titulo">
    <h1>Fritadeiras</h1>
</div>
<hr/>
<br>
<div class="conteudo_infos mx-auto" style="width: 300px;">
    <%= form_with(model: @fritadeira, local: true) do |form| %>
        <% if @fritadeira.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@fritadeira.errors.count, "erro") %> ocorreu ao salvar a categoria:</h2>
                <ul>
                <% @fritadeira.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
                </ul>
            </div>
        <% end %>
        

        <div class="mb-3">
            <%= form.label :modelo, class: "form-label" %>
            <%= form.select :modelo, [["Tacho", "Tacho"], ["Cuba", "Cuba"]], { prompt: "Selecione um modelo" }, class: "form-select" %>
        </div>

        <div class="mb-3">
            <%= form.label :Cod_interno, "Codigo Interno", class: "form-label" %>
            <%= form.text_field :cod_interno, class: "form-control" %>
        </div>

        <div class="mb-3">
            <%= form.label :capacidade, class: "form-label" %>
            <%= form.select :capacidade, Fritadeira.capacidades.keys.map { |key| [key, key] }, { prompt: "Selecione a capacidade" }, class: "form-select" %>
        </div>

        <div class="mb-3">
            <%= form.label :voltagem, class: "form-label" %>
            <%= form.select :voltagem, Fritadeira.voltagems.keys.map { |key| [key.capitalize, key] }, { prompt: "Selecione a voltagem" }, class: "form-select" %>
        </div>

                    
        <div class="mb-3">
            <%= form.label :category_id, "Categoria", class: "form-label" %>
            <select class="form-select" aria-label="Selecione uma categoria" name="fritadeira[category_id]">
                <% Category.all.each do |category| %>
                <% if category.id == 1 %>
                    <option value="<%= category.id %>" selected><%= category.name %></option>
                <% else %>
                    <option value="<%= category.id %>"><%= category.name %></option>
                <% end %>    
                <% end %>
            </select>
        </div>

        <div class="mb-3">
            <%= form.label :classe_id, "Classe", class: "form-label" %>
            <select class="form-select" aria-label="Selecione uma Classe" name="fritadeira[classe_id]">
                <% Classe.all.each do |classe| %>
                <% if classe.id == 2 %> <!-- Verifica se a classe atual é a mesma que está selecionada -->
                    <option value="<%= classe.id %>" selected><%= classe.nome %></option>
                <% else %>
                    <option value="<%= classe.id %>"><%= classe.nome %></option>
                <% end %>
                <% end %>
            </select>
        </div>

        
        <div class="mt-3">
            <%= form.submit 'Salvar', class: "btn btn-primary" %>
            <%= link_to 'Voltar', fritadeiras_path, class: "btn btn-danger" %>
        </div>
    <% end %>
    
</div>  