config/routes.rb
Rails.application.routes.draw do
  get 'saidas/new'
  get 'saidas/create'
  get 'entradas/new'
  get 'entradas/create'
  resources :fritadeiras

  #index da pagina de dashboard
  root 'dashboard#index'

  ### Rotas Category ###
  resources :categories

  ### Rotas Fritadeiras ###
  resources :fritadeiras

  ### Rotas estoque ###
  resources :estoques

  ### Entradas ###
  resources :entradas

  ### Saidas ###
  resources :saidas

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/classe.rb
class Classe < ApplicationRecord
end

app/models/entrada.rb
class Entrada < ApplicationRecord
  belongs_to :estoque
  belongs_to :fritadeira


end

app/models/estoque.rb
class Estoque < ApplicationRecord
  belongs_to :fritadeira
  has_many :entrada, dependent: :destroy
  has_many :saida, dependent: :destroy



end

app/models/fritadeira.rb
class Fritadeira < ApplicationRecord
  belongs_to :category

  enum capacidade: { '3 litros' => 3, '5 litros' => 5, '7 litros' => 7, '10 litros' => 10, '12 litros' => 12, '14 litros' => 14 }
  enum voltagem: { '110v' => 0, '220v' => 1 }


end

app/models/saida.rb
class Saida < ApplicationRecord
  belongs_to :estoque
  belongs_to :fritadeira
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/classe_helper.rb
module ClasseHelper
end

app/helpers/classificacao_helper.rb
module ClassificacaoHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/helpers/estoque_helper.rb
module EstoqueHelper
end

app/helpers/fritadeiras_helper.rb
module FritadeirasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/saidas_helper.rb
module SaidasHelper
end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Erpoint</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= javascript_importmap_tags %>

    <!-- Inclua seu arquivo CSS personalizado aqui -->
    <%= stylesheet_link_tag "style" %>

    <%= javascript_include_tag 'application' %>

    


  </head>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  <body>
    <header class="header">
      <div class="container-fluid">
        <div class="row">
          <div class="col">
            <h1><a href="<%= root_path %>" style="text-decoration: none; color: inherit;">Dashboard</a></h1>
          </div>
          <div class="col text-end">
            <a href="#" class="btn btn-danger">Logout</a>
          </div>
        </div>
      </div>
    </header>
    
    <!-- Barra lateral -->
    <div class="sidebar">
      <ul class="nav flex-column">
        <h5 class="expandable">Categorias</h5>
        <div class="submenu">
          <li class="nav-item">
            <a class="nav-link" href="<%= categories_path %>">Categorias</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_category_path %>">Nova Categoria</a>
          </li>
        </div>
      </ul>
      <hr/>
      <ul class="nav flex-column">
        <h5 class="expandable">Modelos de Fritadeiras</h5>
        <div class="submenu">
          <li class="nav-item">
            <a class="nav-link" href="<%= fritadeiras_path %>">Todos modelos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_fritadeira_path %>">Adicionar Modelo</a>
          </li>
        </div>
      </ul>
      <hr/>
      <ul class="nav flex-column">
        <h5 class="expandable">Controle de Estoque</h5>
        <div class="submenu">
          <li class="nav-item">
            <a class="nav-link" href="<%= estoques_path %>">Gestão Estoque</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_estoque_path %>">Primeira entrada</a>
          </li>
        </div>
      </ul>
      <hr/>            
    </div>
    <hr>

    <div class="conteudo">
    <% if notice %>
        <div class="alert alert-success" role="alert">
            <%= notice %>
        </div>
    <% end %> 

    <% if alert %>
        <div class="alert alert-danger" role="alert">
            <%= alert %>
        </div>
    <% end %>
      <%= yield %>
    </div>  
  </body>
</html>